# Generated by Django 3.1.1 on 2020-09-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abhi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employee',
            new_name='employee1',
        ),
    ]
