# Generated by Django 3.1.1 on 2020-09-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abhi', '0002_auto_20200907_0631'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee1',
            table='employee1',
        ),
    ]
